spring:
  application:
    name: multifactor-authentication
  ssl:
    bundle:
      jks:
        localhost:
          key:
            password: changeit
          keystore:
            location: classpath:server-keystore.p12
            password: changeit
            type: PKCS12
server:
  port: 8443
  ssl:
    enabled: true
    bundle: localhost
  http2:
    enabled: true
  address: server.local

logging:
  level:
    org.springframework.security: trace
    com.webauthn4j: trace
